sudo: required

services:
  - docker

before_install:
  - docker build -t yasar/react-test -f .client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yasar/react-test npm test

after_sucess:
  - docker build -t yasar/multi-client ./client
  - docker build -t yasar/multi-nginx ./nginx
  - docker build -t yasar/multi-server ./server
  - docker build -t yasar/multi-worker ./worker

# Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push to docker hub

  - docker push yasar/multi-client
  - docker push yasar/multi-nginx
  - docker push yasar/multi-server
  - docker push yasar/multi-worker